default: &default
  rules:
  - /\/de\/collections\/?\Z/: "/de/sammlungen"
  - /\/de\/collections\/(?<id>[^\/]+)\Z/: "/de/sammlungen/\\k<id>"
  - /\/de\/sammlungen\/?\Z/: "/de/specials"
  - /\/de\/sammlungen\/(?<id>[^\/]+)\Z/: "/de/specials/\\k<id>"
  - /[^\/]+\/collections\Z/: |
      -> (url) do
        "/foo/bar"
      end

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
